/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as FinancesRouteImport } from './routes/finances'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BarbersRouteImport } from './routes/barbers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesRoute = FinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbersRoute = BarbersRouteImport.update({
  id: '/barbers',
  path: '/barbers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/barbers': typeof BarbersRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/finances': typeof FinancesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/barbers': typeof BarbersRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/finances': typeof FinancesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/barbers': typeof BarbersRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/finances': typeof FinancesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/barbers'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/finances'
    | '/services'
    | '/settings'
    | '/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/barbers'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/finances'
    | '/services'
    | '/settings'
    | '/subscription'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/auth'
    | '/barbers'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/finances'
    | '/services'
    | '/settings'
    | '/subscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  BarbersRoute: typeof BarbersRoute
  CalendarRoute: typeof CalendarRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  FinancesRoute: typeof FinancesRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionRoute: typeof SubscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbers': {
      id: '/barbers'
      path: '/barbers'
      fullPath: '/barbers'
      preLoaderRoute: typeof BarbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  BarbersRoute: BarbersRoute,
  CalendarRoute: CalendarRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  FinancesRoute: FinancesRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionRoute: SubscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
