
INSERT INTO public.tutorial_categories (name, icon, "order")
SELECT 'Experiência do Cliente', 'Sparkles', 11
WHERE NOT EXISTS (SELECT 1 FROM public.tutorial_categories WHERE name = 'Experiência do Cliente');

WITH cats AS (SELECT id, name FROM public.tutorial_categories)
INSERT INTO public.tutorials (title, description, long_description, category_id, type, content_url, level, estimated_time, icon, is_featured, "order")
SELECT * FROM (VALUES
  ('Como funcionam as avaliações pós-atendimento',
   'Envie automaticamente um pedido de avaliação 15 minutos após o atendimento e receba feedback em estrelas.',
   E'O Barbex envia, via WhatsApp, um pedido de avaliação 15 minutos após o atendimento ser concluído.\n\n**Como funciona:**\n1. Ao concluir o atendimento na agenda, um job é enfileirado.\n2. Após 15 min, o cliente recebe um link exclusivo com token único.\n3. Ele avalia em estrelas (1 a 5), pode recomendar e deixar comentário.\n4. Avaliações 5★ recebem automaticamente o cupom **VOLTAMAIS10** (10% off).\n5. Avaliações abaixo de 3★ disparam alerta interno em 24h.\n\n**Onde acompanhar:** menu **Avaliações** — KPIs, moderação e ações em massa.\n\n**Dica:** ative depoimentos aprovados para aparecerem no site público.',
   (SELECT id FROM cats WHERE name='Experiência do Cliente'),
   'document', NULL, 'basico', '4 min', 'Star', true, 1),
  ('Como usar a Comanda Digital',
   'Adicione produtos ao atendimento em andamento e atualize o estoque automaticamente.',
   E'A Comanda Digital inclui produtos vendidos durante o atendimento diretamente no valor final.\n\n**Passo a passo:**\n1. Na agenda, abra o atendimento em andamento.\n2. Clique em **Comanda**.\n3. Busque o produto e selecione a quantidade.\n4. O estoque é decrementado e o valor entra no total do atendimento.\n\n**Regras:**\n- Não é possível vender produtos sem estoque.\n- Cada item vira uma linha em **Vendas de Produtos** com comissão (se configurada).\n- O total do atendimento é recalculado em tempo real.',
   (SELECT id FROM cats WHERE name='Agenda'),
   'document', NULL, 'basico', '3 min', 'ShoppingBag', true, 10),
  ('Como fazer Split de Pagamento',
   'Receba um mesmo atendimento em vários métodos (dinheiro, PIX, cartão) e adicione gorjeta.',
   E'O Split de Pagamento fecha um atendimento combinando várias formas de pagamento.\n\n**Como usar:**\n1. Na conclusão do atendimento, clique em **Dividir Pagamento**.\n2. Adicione valores em Dinheiro, PIX, Débito ou Crédito.\n3. Use o botão **Resto** para preencher o valor restante.\n4. Adicione gorjeta (5%, 10%, 15% ou valor livre).\n5. O sistema valida se a soma bate com o total antes de finalizar.\n\n**Onde aparece:** cada método vira lançamento no financeiro; a gorjeta fica separada e vai para o barbeiro.',
   (SELECT id FROM cats WHERE name='Financeiro'),
   'document', NULL, 'intermediario', '4 min', 'CreditCard', true, 10),
  ('Como ativar a Gorjeta Digital via PIX',
   'Permita que o cliente envie gorjeta direto no PIX do barbeiro após a avaliação.',
   E'Cada barbeiro pode cadastrar sua chave PIX pessoal para receber gorjetas.\n\n**Configuração:**\n1. Vá em **Barbeiros** e edite o profissional.\n2. Cadastre a chave PIX (CPF, e-mail, celular ou aleatória) e o nome do titular.\n\n**Como o cliente usa:**\n- Após avaliar, aparece um card **Gorjeta PIX** com QR Code.\n- Ele copia a chave em um clique ou escaneia pelo banco.\n- O valor cai direto na conta do barbeiro (o Barbex não intermedia).',
   (SELECT id FROM cats WHERE name='Comissões'),
   'document', NULL, 'basico', '3 min', 'HandCoins', false, 10),
  ('Como usar o Check-in por QR Code',
   'Cliente escaneia o QR na recepção e confirma a chegada automaticamente.',
   E'O QR Code de check-in agiliza a recepção.\n\n**Configuração:**\n1. Vá em **Configurações** → aba **Check-in QR**.\n2. Imprima o QR e cole na recepção.\n\n**Fluxo do cliente:**\n1. Ao escanear, abre a página `/checkin` da barbearia.\n2. Informa o WhatsApp e é reconhecido.\n3. O status do próximo agendamento vira **Aguardando**.\n\n**Vantagem:** o barbeiro vê em tempo real quem já chegou.',
   (SELECT id FROM cats WHERE name='Agenda'),
   'document', NULL, 'basico', '3 min', 'QrCode', true, 11),
  ('Como funciona a loja pública de produtos',
   'Venda produtos direto pelo site da barbearia com identificação por WhatsApp e pagamento PIX.',
   E'A loja pública fica em `/{sua-barbearia}` e permite compras sem agendamento.\n\n**Fluxo de compra:**\n1. Cliente escolhe produtos e abre o carrinho.\n2. Pede o **WhatsApp** primeiro — se já existir, reutiliza o cadastro.\n3. Cadastro novo: nome, e-mail e aceite dos termos.\n4. Pagamento por PIX (com QR Code) ou método configurado.\n5. Modal de sucesso com botões para agendar ou acessar o portal.\n\n**Requisitos:** produtos com estoque cadastrados e módulo **Loja** habilitado.',
   (SELECT id FROM cats WHERE name='Produtos'),
   'document', NULL, 'intermediario', '5 min', 'Store', true, 10),
  ('Como instalar o Barbex como App (PWA)',
   'Instale o Barbex no celular e no desktop para acesso rápido sem navegador.',
   E'O Barbex é um PWA — pode ser instalado como app nativo.\n\n**Android / Chrome:**\n1. Abra o Barbex no navegador.\n2. Menu (⋮) → **Instalar app**.\n\n**iPhone / Safari:**\n1. Toque em Compartilhar.\n2. **Adicionar à Tela de Início**.\n\n**Desktop:** ícone de instalação na barra de endereços.\n\nAbre em tela cheia, sem barra do navegador e suporta notificações push.',
   (SELECT id FROM cats WHERE name='Primeiros passos'),
   'document', NULL, 'basico', '2 min', 'Smartphone', false, 10),
  ('Como ativar Notificações Push',
   'Receba avisos de novos agendamentos, mensagens e status mesmo com o app fechado.',
   E'Notificações push funcionam no navegador e no Barbex instalado como PWA.\n\n**Ativação:**\n1. Acesse o portal ou o painel.\n2. No card **Ativar Notificações**, clique em **Permitir**.\n3. Confirme na janela do navegador.\n\n**O que você recebe:**\n- Novos agendamentos\n- Cancelamentos e reagendamentos\n- Confirmações de pagamento\n- Alertas de avaliações negativas (equipe interna)\n\n**Compatibilidade:** Chrome, Edge, Firefox, Safari 16.4+ (iOS instalado como PWA).',
   (SELECT id FROM cats WHERE name='Configurações'),
   'document', NULL, 'basico', '3 min', 'BellRing', false, 10),
  ('Como configurar destinatários internos do WhatsApp',
   'Envie alertas de novos agendamentos e cancelamentos para toda a equipe.',
   E'Além da mensagem para o cliente, o Barbex pode notificar múltiplos números internos.\n\n**Como configurar:**\n1. **Configurações** → **WhatsApp** → **Destinatários Internos**.\n2. Adicione nome, número e quais eventos cada pessoa recebe.\n3. Salve.\n\n**Dica:** use para avisar recepcionistas, gerentes ou o dono sem duplicar mensagens do cliente.',
   (SELECT id FROM cats WHERE name='WhatsApp'),
   'document', NULL, 'basico', '3 min', 'Users', false, 10),
  ('Como usar fluxos conversacionais e botões inteligentes',
   'Adicione botões de ação (Confirmar, Reagendar, Cancelar) nas mensagens automáticas.',
   E'As automações suportam botões interativos que o cliente clica direto no WhatsApp.\n\n**Configuração:**\n1. Em **Automações**, edite um template.\n2. Na aba **Interações**, adicione botões: rótulo + ação (confirmar, reagendar, cancelar, avaliar).\n3. Salve — o próximo envio já traz os botões.\n\n**Como o Barbex reage:** ao clicar, o executor identifica a ação e atualiza o agendamento automaticamente.',
   (SELECT id FROM cats WHERE name='WhatsApp'),
   'document', NULL, 'avancado', '5 min', 'MessageSquare', true, 11),
  ('Como usar a Visão Gerencial e exportar PDF do financeiro',
   'Analise fluxo de caixa, DRE simplificado e exporte relatórios em PDF.',
   E'A tela **Financeiro** ganhou visão gerencial, cupons e exportação.\n\n**O que tem:**\n- **Visão Gerencial:** receita por método, ticket médio, top serviços, gráfico de tendência.\n- **Cupons:** desempenho de cada cupom (usos, desconto, receita gerada).\n- **Exportar PDF:** botão no topo — gera relatório com filtros do período selecionado.\n\n**Filtros:** todos respeitam o intervalo de datas do topo.',
   (SELECT id FROM cats WHERE name='Financeiro'),
   'document', NULL, 'intermediario', '4 min', 'FileBarChart', false, 11),
  ('Como adicionar a Galeria de Fotos ao site público',
   'Mostre fotos do ambiente e trabalhos entre os especialistas e depoimentos.',
   E'A Galeria de Fotos aparece no site público entre **Especialistas** e **Depoimentos**.\n\n**Configuração:**\n1. **Configurações** → aba **Aparência**.\n2. Role até **Galeria de Fotos**.\n3. Envie múltiplas imagens (JPG/PNG).\n4. Salve — o site atualiza automaticamente.\n\n**Recursos:** grid responsivo, lightbox ao clicar, ordem preservada.',
   (SELECT id FROM cats WHERE name='Configurações'),
   'document', NULL, 'basico', '2 min', 'Images', false, 11),
  ('Automações inteligentes de reagendamento e cancelamento',
   'Mensagens diferentes quando quem cancela é o cliente, o barbeiro ou a barbearia.',
   E'O Barbex identifica o **ator** da ação e envia a mensagem correta:\n\n- Cliente cancela → confirmação para o cliente + alerta para a equipe.\n- Barbeiro/Barbearia cancela → desculpas para o cliente com CTA para reagendar.\n- Reagendamento → mostra data antiga e nova (`{{old_date}}` e `{{new_date}}`).\n\n**Como personalizar:**\n1. **Automações** → filtre por **Cancelamento** ou **Reagendamento**.\n2. Edite os 18 templates conforme ator e destinatário.\n3. Use as variáveis disponíveis no editor.',
   (SELECT id FROM cats WHERE name='WhatsApp'),
   'document', NULL, 'avancado', '5 min', 'Repeat', false, 12)
) AS t(title, description, long_description, category_id, type, content_url, level, estimated_time, icon, is_featured, "order")
WHERE NOT EXISTS (SELECT 1 FROM public.tutorials WHERE tutorials.title = t.title);
