ALTER TABLE public.zapi_webhook_debug 
ADD COLUMN IF NOT EXISTS method TEXT,
ADD COLUMN IF NOT EXISTS url TEXT,
ADD COLUMN IF NOT EXISTS content_type TEXT,
ADD COLUMN IF NOT EXISTS query_params JSONB,
ADD COLUMN IF NOT EXISTS path_params JSONB,
ADD COLUMN IF NOT EXISTS raw_body TEXT;