ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS font_family TEXT DEFAULT 'Inter',
ADD COLUMN IF NOT EXISTS font_size TEXT DEFAULT '16px',
ADD COLUMN IF NOT EXISTS font_color TEXT DEFAULT '#000000';
