// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  const isBrowser = typeof window !== 'undefined';
  const SUPABASE_URL = isBrowser ? import.meta.env.VITE_SUPABASE_URL : process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = isBrowser ? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY : process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    if (!isBrowser) {
      console.warn(`[Supabase SSR] Missing env vars. Returning a partial client.`);
      const noop = () => ({ data: { subscription: { unsubscribe: () => {} } } });
      const noopPromise = async () => ({ data: { session: null, claims: null }, error: null });
      return { 
        auth: { 
          onAuthStateChange: noop,
          getSession: noopPromise,
          refreshSession: noopPromise,
          getClaims: noopPromise
        },
        from: () => ({ select: () => ({ eq: () => ({ maybeSingle: noopPromise, order: () => ({}) }) }) }),
        rpc: noopPromise
      } as any;
    }
    const message = `Missing Supabase environment variable(s). Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: isBrowser ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

/**
 * Enhanced Supabase client that handles auth errors globally
 */
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(target, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    const value = Reflect.get(_supabase, prop, receiver);

    // If it's the auth property, just return it
    if (prop === 'auth') return value;

    // Intercept database calls (from, rpc) to inject error handling
    if (prop === 'from' || prop === 'rpc') {
      return (...args: any[]) => {
        const result = value.apply(_supabase, args);
        
        // During SSR, we don't want to wrap thenables for complex retry logic
        if (typeof window === 'undefined') return result;

        // Wrap the thenable/Promise to catch auth errors
        const originalThen = result.then;
        result.then = function(onFullfilled: any, onRejected: any) {
          return originalThen.call(this, async (response: any) => {
            if (response?.error) {
              const err = response.error;
              const msg = (err.message || "").toLowerCase();
              
              if (msg.includes("jwt expired") || msg.includes("invalid jwt") || err.code === "PGRST_AUTH_FAILED") {
                console.warn("[SupabaseProxy] Auth error detected in response:", err);
                
                try {
                  const { data: refreshData } = await _supabase!.auth.refreshSession();
                  if (refreshData?.session) {
                    console.log("[SupabaseProxy] Session refreshed, retrying...");
                    // Retry the exact same call
                    const retryResult = await value.apply(_supabase, args);
                    return onFullfilled(retryResult);
                  }
                } catch (refreshErr) {
                  console.error("[SupabaseProxy] Refresh failed:", refreshErr);
                }
                
                // If we get here, refresh failed or didn't happen
                if (!window.location.pathname.includes('/auth')) {
                  // Using dynamic import for toast to keep SSR clean
                  const { toast } = await import('sonner');
                  toast.error("Sua sessão expirou. Redirecionando...");
                  setTimeout(() => {
                    window.location.href = `/auth?redirect=${encodeURIComponent(window.location.pathname + window.location.search)}`;
                  }, 1500);
                }
              }
            }
            return onFullfilled ? onFullfilled(response) : response;
          }, onRejected);
        };
        
        return result;
      };
    }

    return value;
  },
});



